# Generated by Django 5.1.3 on 2024-11-13 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='translationstring',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation_strings', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='translationstring',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='project.language'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='notification_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_notifications', to='project.notificationtemplate'),
        ),
        migrations.AddField(
            model_name='usernotification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usernotificationoption',
            name='user_notification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='project.usernotification'),
        ),
        migrations.AddField(
            model_name='usernotificationsetting',
            name='notification_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to='project.notificationtemplate'),
        ),
        migrations.AddField(
            model_name='usernotificationsetting',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='translationstring',
            index=models.Index(fields=['object_id'], name='idx_cxid'),
        ),
        migrations.AddIndex(
            model_name='translationstring',
            index=models.Index(fields=['content_type'], name='idx_content_type_id'),
        ),
        migrations.AddIndex(
            model_name='translationstring',
            index=models.Index(fields=['language'], name='idx_language_id'),
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['user'], name='idx_un_uid'),
        ),
        migrations.AddIndex(
            model_name='usernotification',
            index=models.Index(fields=['notification_template'], name='idx_un_nt_id'),
        ),
        migrations.AddIndex(
            model_name='usernotificationoption',
            index=models.Index(fields=['user_notification'], name='idx_user_notification_id'),
        ),
        migrations.AddIndex(
            model_name='usernotificationsetting',
            index=models.Index(fields=['user'], name='idx_user_id'),
        ),
        migrations.AddIndex(
            model_name='usernotificationsetting',
            index=models.Index(fields=['notification_template'], name='idx_uns_nt_id'),
        ),
    ]
