# Generated by Django 5.1.3 on 2024-11-22 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('project', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translationstring',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='translation_strings', to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='translationstring',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='languages', to='project.language'),
        ),
        migrations.AlterUniqueTogether(
            name='translationstring',
            unique_together={('content_type', 'object_id', 'translation_field_id', 'language')},
        ),
    ]
