# Generated by Django 5.1.3 on 2024-11-26 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('project', '0003_alter_translationstring_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationtemplate',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='translationstring',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='translationstring',
            name='translation_field_id',
            field=models.IntegerField(choices=[('name', 1), ('title', 2), ('description', 3), ('text', 4), ('question', 5), ('answer', 6), ('additional', 7)], default=1),
        ),
    ]
